# -*- coding: utf-8 -*-
from .fields import *

types = {
	0: ("NPC Kill",
		ForeignKey("npc", "creaturecache"),
		IntegerField("amount"),
		UnknownField("value3"),
		UnknownField("value4"),
		UnknownField("value5"),
		UnknownField("value6"),
	),
	1: ("Battleground Win",
		ForeignKey("instance", "map"),
		IntegerField("amount"),
		UnknownField("value3"),
		ForeignKey("instance2", "map"),
		UnknownField("value5"),
		ForeignKey("instance3", "map"),
	),
	5: ("Level Character",
		UnknownField("value1", unused=True),
		IntegerField("level"),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	7: ("Level Skill",
		ForeignKey("skill", "skillline"),
		IntegerField("level"),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	8: ("Complete Achievement",
		ForeignKey("achievement", "achievement"),
		UnknownField("value2"),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	9: ("Complete Quest Amount",
		UnknownField("value1", unused=True),
		IntegerField("amount"),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	10: ("Complete Quest Daily",
		UnknownField("value1", unused=True),
		DurationField("days", unit="days"),
		UnknownField("value3"),
		UnknownField("value4", unused=True),
		UnknownField("value5"),
		UnknownField("value6", unused=True),
	),
	11: ("Complete Quest Amount (incremental)",
		IntegerField("zone"), #TODO fk
		IntegerField("amount"),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	13: ("Deal Damage",
		UnknownField("value1", unused=True),
		IntegerField("damage"),
		UnknownField("value3"),
		ForeignKey("instance", "map"),
		UnknownField("value5"),
		ForeignKey("instance2", "map"),
	),
	14: ("Complete Daily Quest",
		UnknownField("value1", unused=True),
		IntegerField("amount"),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	15: ("Battleground Played",
		ForeignKey("instance", "map"),
		UnknownField("value2", unused=True),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	16: ("Death Instance",
		ForeignKey("instance", "map"),
		UnknownField("value2", unused=True),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	17: ("Death Situation",
		UnknownField("value1", unused=True),
		UnknownField("value2", unused=True),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	18: ("Death Instance Size",
		IntegerField("groupsize"),
		UnknownField("value2", unused=True),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	19: ("Completed Instance Size",
		IntegerField("groupsize"),
		UnknownField("value2", unused=True),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	20: ("Death NPC",
		ForeignKey("npc", "creaturecache"),
		UnknownField("value2", unused=True),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	23: ("Death PVP",
		UnknownField("value1", unused=True),
		UnknownField("value2", unused=True),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	24: ("Fall Distance",
		UnknownField("value1", unused=True),
		IntegerField("distance"), #distancefield?
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	26: ("Death Environment",
		UnknownField("value1"),
		UnknownField("value2", unused=True),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	27: ("Complete Quest",
		ForeignKey("quest", "questcache"),
		UnknownField("value2"),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5"),
		UnknownField("value6", unused=True),
	),
	28: ("Receive Spell",
		ForeignKey("spell", "spell"),
		IntegerField("amount"),
		UnknownField("value3"),
		UnknownField("value4"),
		UnknownField("value5"),
		UnknownField("value6"),
	),
	29: ("Cast Spell",
		ForeignKey("spell", "spell"),
		IntegerField("amount"),
		UnknownField("value3"),
		UnknownField("value4"),
		UnknownField("value5"),
		UnknownField("value6"),
	),
	30: ("PVP Objective", # TODO
		UnknownField("value1"),
		UnknownField("value2"),
		UnknownField("value3"),
		UnknownField("value4"),
		UnknownField("value5"),
		UnknownField("value6"),
	),
	31: ("PVP Kill", # TODO
		UnknownField("value1"),
		UnknownField("value2"),
		UnknownField("value3"),
		UnknownField("value4"),
		UnknownField("value5"),
		UnknownField("value6"),
	),
	32: ("Arena Win", # TODO
		UnknownField("value1"),
		UnknownField("value2"),
		UnknownField("value3"),
		UnknownField("value4"),
		UnknownField("value5"),
		UnknownField("value6"),
	),
	33: ("Arena Match", # TODO
		UnknownField("value1"),
		UnknownField("value2"),
		UnknownField("value3"),
		UnknownField("value4"),
		UnknownField("value5"),
		UnknownField("value6"),
	),
	34: ("Learn Spell",
		ForeignKey("spell", "spell"),
		UnknownField("value2", unused=True),
		UnknownField("value3", unused=True),
		UnknownField("value4", unused=True),
		UnknownField("value5", unused=True),
		UnknownField("value6", unused=True),
	),
	
}
